#!/usr/bin/env bash
# Installs the commit-msg hook that auto-bumps package.json version.
# Called by `npm prepare` after `npm install`.

set -e

REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null) || exit 0
HOOK="$REPO_ROOT/.git/hooks/commit-msg"

cat > "$HOOK" << 'HOOKEOF'
#!/usr/bin/env bash
# Auto-generated by scripts/install-hooks.sh — do not edit manually.
REPO_ROOT=$(git rev-parse --show-toplevel)
bash "$REPO_ROOT/scripts/bump-version.sh" "$1"
HOOKEOF

chmod +x "$HOOK"
echo "install-hooks: commit-msg hook installed"
